### ISSUE TITLE
建议将博客中的代码行号显示去掉

### ISSUE THREAD

**Issue by forrestchang** [sixwha1e/sixwha1e.github.io#2]
如果实用的是`Hexo`的话，编辑`_config.yml`，找到以下内容

``` yaml
highlight:
  enable: true
  line_number: false  #将这条属性设为false
  tab_replace:
```

因为使用的highlight.js对行号的支持并不是很好，而且某些主题也不支持行号的显示。

---

另外的建议：
1. 添加百度统计和Google统计的功能
2. 添加Duoshuo评论或者Disqus评论的功能（很显然后面一种bigger更高）

主题挺漂亮╮(￣▽￣)╭
